# Site settings
title: Dover Run Club
description: >-
  Tuesday nights at 6pm from The Brick in Dover, NH.
  A community of runners exploring a variety of routes â€” all paces welcome!
baseurl: "/dover-run-club-website" # the subpath of your site, e.g. /blog
url: "https://dekay2001.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Settings
logo: /assets/images/dpr-group-photo.jpg
social:
  name: Dover Run Club
  links:
    - https://www.strava.com/clubs/1768701

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Collections for organizing content
collections:
  events:
    output: true
    permalink: /events/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "page"
